name: spotdl_downloader
description: "Full offline Spotify Downloader powered by spotdl"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Storage & Files
  path_provider: ^2.0.11
  sqflite: ^2.3.0
  shared_preferences: ^2.2.2

  # State Management
  provider: ^6.1.1

  # Permissions
  permission_handler: ^11.1.0

  # Sharing & File Opening
  share_plus: ^7.2.1
  open_filex: ^4.3.4

  # Utils
  intl: ^0.19.0
  google_fonts: ^6.1.0

  # Icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
